service: default

runtime: nodejs20

env: standard

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

entrypoint: node server.js

handlers:
  - url: /.*
    script: auto

env_variables:
  NODE_ENV: production
  PORT: 8080

# NEXT_PUBLIC_API_URL is loaded from Google Secret Manager or defaults
# See setup-secrets.sh for setting up secrets
