service: backend

runtime: nodejs20

env: standard

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

entrypoint: node dist/backend/src/index.js

handlers:
  - url: /.*
    script: auto

env_variables:
  NODE_ENV: production
  PORT: 8080
  # Environment variables are set via gcloud during deployment
  # See .github/workflows/deploy-app-engine.yml
